Fine-tuning scripts for exit codes

diff --git a/backupS/backupscriptf b/backupS/backupscriptf
--- a/backupS/backupscriptf
+++ b/backupS/backupscriptf
@@ -3,7 +3,7 @@ if [ "$#" -ne 3 ] ; then
 echo "ERROR: 3 arguments are required"
 echo "Usage: ./backup.sh <source> <backup_directory> <number>"
 echo "ATTENTION! Number represents the number of days; all backup archives created before the specified date will be deleted. For example, if you enter 7, all backups older than 7 days will be deleted."
-exit 1
+exit 3
 fi
 SOURCE="$1"
 BACKUP_DIR="$2"
@@ -11,17 +11,27 @@ RETENTION_DAYS="$3"
 
 if [[ ! -f "$SOURCE" && ! -d "$SOURCE" ]]; then
     echo "ERROR: Source '$SOURCE' not found"
-    exit 1
+    exit 3
 fi
 
 if [[ ! -r "$SOURCE" ]]; then
     echo "ERROR: $SOURCE does not exist or you do not have permission to access it"
-    exit 1
+    exit 3
+fi
+
+if [[ ! -d "$BACKUP_DIR" ]]; then
+    echo "ERROR: Backup directory '$BACKUP_DIR' does not exist"
+    exit 3
+fi
+
+if [[ ! -w "$BACKUP_DIR" ]]; then
+    echo "ERROR: You do not have permission to write to '$BACKUP_DIR'"
+    exit 3
 fi
 
 if ! [[ "$RETENTION_DAYS" =~ ^[0-9]+$ ]]; then
     echo "ERROR: Retention days must be a number"
-    exit 1
+    exit 3
 fi
 
 CURRENT_DATE=$(date +%Y-%m-%d_%H_%M_%S)
@@ -37,13 +47,13 @@ if tar -czf "$FULL_ARCHIVE_ROAD" "$SOURCE" ; then
     echo "Archive size: $FILE_SIZE"
 else 
     echo "Oops, we had a problem creating the archive"
-    exit 1
+    exit 2
 fi
 }
 delete_old_backups() {
 if ! find "$BACKUP_DIR" -type f -name "backup_*.tar.gz" -mtime +"$RETENTION_DAYS" -delete ; then
 echo "ERROR: Unable to delete old archives"
-exit 1
+exit 2
 fi
 }
 create_backup
